global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']  # optional

  - job_name: 'autoscaler'
    metrics_path: /metrics
    static_configs:
      - targets: ['autoscaler-backend:8081']
